// !!! This is a file automatically generated by hipify!!!
#pragma once
#include <hip/hip_runtime.h>
#define NVML_NO_UNVERSIONED_FUNC_DEFS
#include <rocm_smi/rocm_smi.h>

#define C10_HIP_DRIVER_CHECK(EXPR)                                        \
  do {                                                                     \
    hipError_t __err = EXPR;                                                 \
    if (__err != hipSuccess) {                                           \
      const char* err_str;                                                 \
      hipError_t get_error_str_err C10_UNUSED =                              \
          c10::hip::DriverAPI::get()->hipGetErrorString_(__err, &err_str); \
      if (get_error_str_err != hipSuccess) {                             \
        AT_ERROR("HIP driver error: unknown error");                      \
      } else {                                                             \
        AT_ERROR("HIP driver error: ", err_str);                          \
      }                                                                    \
    }                                                                      \
  } while (0)

#define C10_FORALL_DRIVER_LIBRARIES(_) \
  _("libcuda.so", 0)                   \
  _("libnvidia-ml.so.1", 1)

#define C10_FORALL_DRIVER_API(_)         \
  _(cuMemAddressReserve, 0)              \
  _(cuMemRelease, 0)                     \
  _(cuMemMap, 0)                         \
  _(cuMemAddressFree, 0)                 \
  _(cuMemSetAccess, 0)                   \
  _(cuMemUnmap, 0)                       \
  _(cuMemCreate, 0)                      \
  _(hipGetErrorString, 0)                 \
  _(nvmlInit_v2, 1)                      \
  _(nvmlDeviceGetHandleByPciBusId_v2, 1) \
  _(nvmlDeviceGetComputeRunningProcesses, 1)

namespace c10 {
namespace hip {

struct DriverAPI {
#define CREATE_MEMBER(name, n) decltype(&name) name##_;
  C10_FORALL_DRIVER_API(CREATE_MEMBER)
#undef CREATE_MEMBER
  static DriverAPI* get();
};

} // namespace hip
} // namespace c10
